Add ability to read auth from file
svenstaro/miniserve pull request #1179
Opened 2023-07-21 06:01 UTC by proudmuslim-dev

Usage: 

```
$ miniserve --auth-file auth.txt
```

Example auth.txt content

```
joe:123
bob:sha256:a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3
bill:
```

Related issue: #980

2023-07-25 19:49 UTC, svenstaro requested changes
Very cool, I think this would be a good addition. Please fix my comments and then make sure to also update the README in a separate commit.

2023-07-25 19:49 UTC, svenstaro commented on src/args.rs
> +    /// Read authentication values from a file.
```suggestion
    /// Read authentication values from a file
```

2023-07-25 19:49 UTC, svenstaro commented on src/args.rs
> +    /// Read authentication values from a file.
Also please describe the format of the file.

2023-08-03 05:30 UTC, svenstaro commented
Are you still working on this?

2023-08-03 18:10 UTC, proudmuslim-dev commented
I would have squashed some of those commits, but I don't currently have my SSH or my GPG keys set up so I'm limited to the web interface. Sorry about that :sweat_smile:

2023-08-06 19:52 UTC, svenstaro requested changes
Sorry I didn't say this earlier but I'd like to see a test for this. It's a security feature so it should definitely be tested.

2023-08-07 23:53 UTC, proudmuslim-dev commented
Alright, just give me some time

2023-08-21 03:06 UTC, svenstaro commented
Thanks, great work! I'll merge this and clean it up a little but I don't want to drag merging this out further.

2023-08-21 03:06 UTC, merged

2023-09-02 17:05 UTC, proudmuslim-dev commented
Anytime! I realize now that the tests could've been done better, apologies

2023-09-02 22:27 UTC, svenstaro commented
If you'd like to clean it up in some fashion, I'll surely accept a follow-up!