Add pretty urls
svenstaro/miniserve pull request #1193
Opened 2023-08-06 08:31 UTC by nlopes

This adds a new flag namely `--pretty-urls` that when enabled will serve the equivalent `.html` if it exists.

Very much the same approach that [`netlify`
uses](https://docs.netlify.com/site-deploys/post-processing/).

It can be quite useful when having hrefs like `/about` serve `/about.html`.

2023-08-06 08:32 UTC, nlopes commented
Hi 👋 

I don't believe this was a feature ever requested or in the issue tracker (that I was able to find) but it's one that I use myself.
Happy to keep this as a branch on my own but I thought it would be a nice little feature for `miniserve`.

Feel free to completely discard if you don't think it is something you want to support.

2023-08-06 19:49 UTC, svenstaro requested changes
Seems like a cool feature! Good code too, just small nits.

2023-08-07 13:45 UTC, svenstaro approved these changes

2023-08-07 13:46 UTC, svenstaro commented
Good work!

2023-08-07 13:46 UTC, merged