Set sorting order and method with arguments
svenstaro/miniserve pull request #1308
Opened 2024-01-09 19:53 UTC by ElliottLandsborough

2024-01-09 21:14 UTC, svenstaro commented
Cool! Could you add a description for what it is supposed to do and why? For example, why aren't the current sorters not sufficient? I suppose the idea is to provide a sorting default?

2024-01-10 20:03 UTC, ElliottLandsborough commented
> Cool! Could you add a description for what it is supposed to do and why? For example, why aren't the current sorters not sufficient? I suppose the idea is to provide a sorting default?

I have updated the description - you are right, I want to be able to set the default sort type and order.

The chevrons _may_ have been pointing in the wrong direction too so I have included the change. This is not a big deal to me and it is probably open to interpretation.

2024-01-10 20:04 UTC, svenstaro commented
Code looks perfect. Can I somehow convince you to write a test for this?

2024-01-10 21:09 UTC, ElliottLandsborough commented
> Code looks perfect. Can I somehow convince you to write a test for this?

I've added a test, fixed some bugs, updated some comments.

2024-01-11 03:36 UTC, svenstaro requested changes
Looks great, just one comment about the tests.

2024-01-11 03:36 UTC, svenstaro commented on tests/navigation.rs
> +#[case(server(&["--default-sorting-method", "date", "--default-sorting-order", "desc"]))]
Can you add a second case where you order the other way and demonstrate that this works?

2024-01-13 00:22 UTC, svenstaro commented on tests/navigation.rs
> +
Wouldn't it be better to have a test that checks whether the default sorting works as expected? Sort it one way and then compare it against an expected order and then sort it another way and expect the order to be reversed.

2024-01-13 00:22 UTC, svenstaro commented
I'm happy to merge this and release a new version of miniserve once the test is a bit more useful.

2024-01-13 02:46 UTC, ElliottLandsborough commented
> I'm happy to merge this and release a new version of miniserve once the test is a bit more useful.

Tests have been updated 😃

2024-01-13 03:54 UTC, svenstaro requested changes

2024-01-13 03:54 UTC, svenstaro commented on tests/utils/mod.rs
> +pub fn get_link_hrefs_from_text_with_prefix(document: &Document, text: &str) -> Vec<String> {
```suggestion
pub fn get_link_hrefs_from_text_with_prefix(document: &Document, prefix: &str) -> Vec<String> {
```

2024-01-13 03:54 UTC, svenstaro commented on tests/utils/mod.rs
> +/// Return the href attributes of all links that start with the specified prefix `text`.
```suggestion
/// Return the href attributes of all links that start with the specified `prefix`.
```

2024-01-13 03:55 UTC, svenstaro commented on tests/navigation.rs
> +    let slash = String::from("/");
I'm not sure how I feel about this since we only really need it at a single place. Maybe just create this where it needs to be and remove this?

2024-01-13 04:36 UTC, svenstaro commented
I'm making the last few bits of changes myself. Thanks for the contribution!

2024-01-13 04:36 UTC, merged

2024-01-13 16:35 UTC, svenstaro commented
Happy to hear! Check my changes to your code as well. I think I improved it somewhere and it's now pretty neat.