draft: add read-only webdav support
svenstaro/miniserve pull request #1415
Opened 2024-05-13 04:45 UTC by ahti

2024-09-22 01:32 UTC, svenstaro requested changes
The webdav functionality should likely be put behind a flag. I suppose most people wouldn't want to run it with webdav activated.

Also, can you produce a test that shows that webdav at least works in _some_ fashion?

2024-09-22 01:32 UTC, svenstaro commented on src/webdav_fs.rs
> +use std::path::{Component, Path};
Give this module a description.

2024-09-22 01:32 UTC, svenstaro commented on src/webdav_fs.rs
> +}
Give this a proper description of what this is supposed to do and why we need it.

2024-09-22 01:32 UTC, svenstaro commented on src/webdav_fs.rs
> +fn check_path(path: &DavPath) -> bool {
Describe what the idea here is.

2024-09-22 01:32 UTC, svenstaro commented
Please rebase this!

2025-01-11 04:33 UTC, ahti commented on src/main.rs
> +        // use routing guard so propfind and options requests fall through to the webdav handler
The WebDAV spec [requires](http://www.webdav.org/specs/rfc4918.html#HEADER_DAV):
> All DAV-compliant resources must return the DAV header with compliance-class "1" on all OPTIONS responses.

Actix-files [only handles HEAD and GET](https://github.com/actix/actix-web/blob/0fafb486d4877df3d505ea6533765af499d99a5e/actix-files/src/service.rs#L105) either way, so I don't think this needs to change.

2025-01-11 04:35 UTC, ahti commented on src/main.rs
> +                web::resource("/{tail:.*}")
Using just "/.*" for the path, actix-web prints a bunch of "[WARN] Tail segments must have names. Consider `.../{tail}*`. This may become a panic in the future.".

2025-01-11 21:54 UTC, svenstaro requested changes
I'd like to see you use a real webdav client to check whether this does something useful. I think [reqwest_dav](https://github.com/niuhuan/reqwest_dav) would be suitable. Also I'd like to see you handle:
- Single file serving mode ([new_file](https://docs.rs/dav-server/latest/dav_server/localfs/struct.LocalFs.html#method.new_file) seems to already to this)
- `--route-prefix`/`--random-route`
- `--no-symlinks`
- Optional: `--mkdir`
- Optional: `--upload-files`

2025-02-06 02:03 UTC, svenstaro approved these changes
Excellent work, merging as-is!

2025-02-06 02:03 UTC, merged