Disable Content-Disposition header
svenstaro/miniserve pull request #477
Opened 2021-03-24 12:37 UTC by aliemjay

Otherwise, symlink files would be served with the filename of the
pointed-to file.

This should fix #462.

2021-03-25 09:30 UTC, aliemjay commented
The URL for a symlink file is currently treated like a directory: They have a trailing "/" and may contain some query parameters (e.g. sorting method). For example: `http://localhost:1212/sss.pdf/?sort=size&order=asc`. Because if this, when downloading with some download managers (e.g. arias2c or wget), the filename will always be "index.html" and may contain some parameters.

This should be fixed by #479

2021-03-27 01:00 UTC, svenstaro commented
Could you rebase this?

2021-03-27 19:04 UTC, svenstaro commented
I took a look at this and it does work. I'd just like to discuss: Do you think it would be better to set the proper `filename="symlink-name"` attribute in the `content-disposition` header or to just get rid of it entirely? We do lose the flexibility of being able to tell the browser what to try to display.

2021-03-27 19:36 UTC, aliemjay commented
I've considered this, but after looking at actix-files sources, there seems to be no feasible way to do so. actix-files always uses the canonical path of the file to set the content-dispostion header.

2021-03-27 23:32 UTC, svenstaro commented
Alright then. Feel like adding a check to an existing test or a new test for this? I'd merge without it if you don't want to add a test condition for such a small change.

2021-03-29 23:24 UTC, svenstaro commented
As an aside: You might wanna report a feature request over at actix-files for this particular case. It _would_ be nicer to be able to set the proper name, after all.

2021-03-29 23:28 UTC, svenstaro requested changes
Just some tiny nits. :)

2021-03-29 23:28 UTC, svenstaro commented on tests/serve_request.rs
> +        let resp = reqwest::blocking::get(format!("http://localhost:8080/{}", file))?
For specific checks like this, I like seeing a comment as to _why_ we're checking for this particular thing.

2021-03-29 23:28 UTC, svenstaro commented on src/main.rs
> +                    .disable_content_disposition()
Now what this condition block is growing, how about trying to unify it a little? Maybe something like:
```rust
let files = actix_files::Files::new(&full_route, path).show_files_listing().disable_content_disposition();
if show_hidden {
    let files = files.use_hidden_files();
}
```
Would that work?

2021-04-05 08:11 UTC, svenstaro commented
Do you want to have a shot and try to solve this upstream? I think I'm ok integrating a mid-term fix until this is properly fixed upstream, though.

2021-04-05 14:53 UTC, aliemjay commented
I don't know if I would solve it upstream, but I've just tried to implement the requested changed.

2021-04-18 02:56 UTC, svenstaro commented
So with https://github.com/actix/actix-web/pull/2156 merged and therefore your issue https://github.com/actix/actix-web/issues/2128 fixed in actix itself, I believe it'd be proper to await the actix-web 4 release. What do you think?

2021-04-18 03:05 UTC, aliemjay commented
I agree. Closing...

2021-04-18 03:05 UTC, closed without merging