[wip] Update actix web to v4.0.0-beta.16
svenstaro/miniserve pull request #677
Opened 2021-12-28 01:04 UTC by Jikstra

Currently wip/draft as I couldn't add HttpAuthentication middleware and for the map_error_page method i couldn't retrieve the error string.

2021-12-28 01:06 UTC, Jikstra commented on src/config.rs
> +                .with_single_cert(vec!(rustls::Certificate(cert_chain)), rustls::PrivateKey(keys.remove(0)))?;
I think I did well with refactoring this code, but please carefully review as I have not too much clue about tls things.

2021-12-28 01:23 UTC, aliemjay requested changes
Thanks for taking this forward.

2021-12-28 01:23 UTC, aliemjay commented on src/main.rs
> +        .message_body(BoxBody::new(logo))
```suggestion
        .body(logo)
```

2021-12-28 01:23 UTC, aliemjay commented on src/listing.rs
> +                HttpResponse::UriTooLong().body(BoxBody::new(""))
```suggestion
                HttpResponse::UriTooLong().finish() 
```

2021-12-28 01:23 UTC, aliemjay commented on src/errors.rs
> +    let error_msg = "heeelp!";
I think we need to make this fn async and use actix_web::body::to_bytes

2021-12-28 01:24 UTC, aliemjay commented on src/errors.rs
> +    let error_msg = "heeelp!";
or alternatively use MessageBody::try_into_bytes

2021-12-28 01:30 UTC, Jikstra commented
> Thanks for taking this forward.

Thanks for your initial pr :)

2021-12-28 01:31 UTC, Jikstra commented
@aliemjay I think in your pr one test failed because of a regression in actix-web. To me it looked like the test was a bit anyways? Lot's of special chars if I remember correctly. Probably we can just kick out that test?

2021-12-28 01:50 UTC, aliemjay commented
> Probably we can just kick out that test?

I don't think so. It is there for a reason and, if I remember, it fixed a reported issue. Anyway, it is on the plan for v4.

2021-12-28 01:53 UTC, aliemjay commented
Oh, I forgot to note that most of my PR changes are now merged because I split it into a different PR. You may want to resolve the conflicts, but I think it is cleaner to rebase the last commits.

2021-12-28 02:14 UTC, Jikstra commented
> Oh, I forgot to note that most of my PR changes are now merged because I split it into a different PR. You may want to resolve the conflicts, but I think it is cleaner to rebase the last commits.

I think I successfully rebased this pr :)

2021-12-28 02:24 UTC, Jikstra commented
Soooo, all looks good now besides this one failing test. @aliemjay could we somehow encode those chars on our own in miniserve or do we need to wait for actix_web to fix this?

2021-12-28 02:31 UTC, aliemjay commented
> do we need to wait for actix_web to fix this?

I believe yes. There is nothing we can do in our part. I'll push for it and try to get it soon.

2022-01-04 16:12 UTC, aliemjay commented
Actix-web beta.19 is now out with a fix to the regression.

2022-01-04 17:06 UTC, Jikstra commented
Awesome!

2022-02-04 14:51 UTC, svenstaro commented
Hey, how are we looking on the fix? The actix-web 4 rc is out so now might be a good time to get this merged.

2022-02-04 15:52 UTC, Jikstra commented
I will not have time to work on this before mid of march, so feel free to just continue this pr whoever wants to :)

2022-02-06 09:27 UTC, merged