Implement --route-prefix to set specific route prefix
svenstaro/miniserve pull request #682
Opened 2021-12-29 03:10 UTC by Jikstra

2021-12-29 03:17 UTC, Jikstra commented on tests/serve_request.rs
> +) -> Result<(), Error> {
On the old pr @aliemjay mentioned having more test cases. I don't really understand that case macro, the first two booleans make me wonder. Can someone help me with this?

2021-12-29 07:21 UTC, aliemjay approved these changes
Other than a few nitpicks :) it looks good.

2021-12-29 07:21 UTC, aliemjay commented on src/config.rs
> +            (Some(prefix), _) => format!("/{}", prefix),
```suggestion
            (Some(prefix), _) => format!("/{}", prefix.trim_matches('/')),
```

This should normalize the prefix to handle the case of leading and trailing slash. In this case, the previous match arm should be removed.

2022-01-03 19:33 UTC, Jikstra commented
@aliemjay thank you, applied your requested changes :)

2022-01-04 15:45 UTC, Jikstra commented
@svenstaro can you have a look? Not so much in the mood to rebase this another time.

2022-01-04 16:11 UTC, aliemjay requested changes

2022-01-04 16:11 UTC, aliemjay commented on src/config.rs
> +            (Some(prefix), _) if prefix.starts_with('/') => prefix,
```suggestion
```

this special case should be handled by the next match arm.

2022-01-05 17:25 UTC, Shados commented
@Jikstra The dynamically-generated `css_route` and `favicon_route` need to be prefixed, as well.

2022-01-05 17:51 UTC, Shados commented
Also, the route prefix should be appended to the root dir breadcrumb, for the generated directory listing page.

2022-02-04 14:52 UTC, svenstaro commented
> @svenstaro can you have a look? Not so much in the mood to rebase this another time. Also, a little bit off topic, but are you interested in having more maintainers for this project?

Looking now. Yes, I'd rather appreciate more maintainers on this project if you're up. Do you have any chat communication channels so that we can coordinate?

2022-02-04 15:03 UTC, svenstaro approved these changes
Thanks, this is great. Sorry for delaying for so long.

2022-02-04 15:05 UTC, svenstaro requested changes
I found the same issues that @Shados found, apart from that it seems good to merge for me.

2022-02-05 13:06 UTC, Jikstra commented
> > @svenstaro can you have a look? Not so much in the mood to rebase this another time. Also, a little bit off topic, but are you interested in having more maintainers for this project?
> 
> Looking now. Yes, I'd rather appreciate more maintainers on this project if you're up. Do you have any chat communication channels so that we can coordinate?

I will be busy until march, but then I'm up. You can send me a message on jikstra at riseup.net

2022-02-06 12:23 UTC, closed without merging