Change DateTime format
svenstaro/miniserve pull request #949
Opened 2022-10-23 15:55 UTC by IvkinStanislav

Fix issues [440](https://github.com/svenstaro/miniserve/issues/440) and [748](https://github.com/svenstaro/miniserve/issues/748)

2022-11-10 20:19 UTC, svenstaro requested changes
Thanks, this is good stuff. I'd just like the format to be a adjusted slightly.

2022-11-10 20:19 UTC, svenstaro commented on src/renderer.rs
> +        .map(|date_time| date_time.format("%Y/%m/%d %H:%M:%S %:z").to_string())
Let's have these be displayed in the more traditional dash separated format:
```suggestion
        .map(|date_time| date_time.format("%Y-%m-%d %H:%M:%S %:z").to_string())
```
Alternatively, you could also use `to_rfc2822()` which might be more readable to some people. Your call.

2022-11-10 20:41 UTC, IvkinStanislav commented
> Thanks, this is good stuff. I'd just like the format to be a adjusted slightly.

Ready

2022-11-11 00:27 UTC, svenstaro commented
Thanks!

2022-11-11 00:27 UTC, merged